#Track properties available for both pixel tracks and "full" tracks
trackProperties = [
    "GeneralProperties/Chi2Prob_GenTk",
    "GeneralProperties/Chi2oNDFVsEta_ImpactPoint_GenTk",
    "GeneralProperties/Chi2oNDFVsNHits_ImpactPoint_GenTk",
    "GeneralProperties/Chi2oNDFVsPt_ImpactPoint_GenTk",
    "GeneralProperties/Chi2oNDF_GenTk",
    "GeneralProperties/DeltaZToPVZoom_GenTk",
    "GeneralProperties/DistanceOfClosestApproachToPVZoom_GenTk",
    "GeneralProperties/DistanceOfClosestApproachToBS_GenTk",
    "GeneralProperties/DistanceOfClosestApproachToPVVsPhi_GenTk",
    "GeneralProperties/DistanceOfClosestApproachToBSVsPhi_GenTk",
    "GeneralProperties/NumberOfTracks_GenTk",
    "GeneralProperties/NumberOfTracksVsLS_GenTk",
    "GeneralProperties/NumberOfGoodPVtxVsLS_GenTk",
    "GeneralProperties/NumberOfGoodPVtxWO0VsLS_GenTk",
    "GeneralProperties/NumberOfLayersPerTrackVsEta_ImpactPoint_GenTk",
    "GeneralProperties/NumberOfLayersPerTrackVsPhi_ImpactPoint_GenTk",
    "GeneralProperties/NumberOfRecHitsPerTrackVsEta_ImpactPoint_GenTk",
    "GeneralProperties/NumberOfRecHitsPerTrackVsPhi_ImpactPoint_GenTk",
    "GeneralProperties/NumberOfRecHitsPerTrackVsLS_GenTk",
    "GeneralProperties/NumberOfValidRecHitsPerTrackVsEta_ImpactPoint_GenTk",
    "GeneralProperties/NumberOfValidRecHitsPerTrackVsPhi_ImpactPoint_GenTk",
    "GeneralProperties/NumberOfValidRecHitsPerTrackVsPt_ImpactPoint_GenTk",
    "GeneralProperties/TrackPtErrOverPtVsEta_ImpactPoint_GenTk",
    "GeneralProperties/stoppingSourceVSeta_GenTk",
    "GeneralProperties/stoppingSourceVSphi_GenTk",
    "GeneralProperties/xPointOfClosestApproachToPV_GenTk",
    "GeneralProperties/xPointOfClosestApproach_GenTk",
    "GeneralProperties/xPointOfClosestApproachVsZ0wrt000_GenTk",
    #"GeneralProperties/xPointOfClosestApproachVsZ0wrtBS_GenTK",
    "GeneralProperties/xPointOfClosestApproachVsZ0wrtPV_GenTk",
    "GeneralProperties/yPointOfClosestApproachToPV_GenTk",
    "GeneralProperties/yPointOfClosestApproach_GenTk",
    "GeneralProperties/yPointOfClosestApproachVsZ0wrt000_GenTk",
    #"GeneralProperties/yPointOfClosestApproachVsZ0wrtBS_GenTK",
    "GeneralProperties/yPointOfClosestApproachVsZ0wrtPV_GenTk",
    "GeneralProperties/zPointOfClosestApproachToPV_GenTk",
    "GeneralProperties/zPointOfClosestApproach_GenTk",
    "GeneralProperties/zPointOfClosestApproachVsPhi_GenTk",
    "GeneralProperties/TrackEta_ImpactPoint_GenTk",
    "GeneralProperties/TrackP_ImpactPoint_GenTk",
    "GeneralProperties/TrackPt_ImpactPoint_GenTk",
    "GeneralProperties/TrackPhi_ImpactPoint_GenTk",
    "GeneralProperties/TrackPz_ImpactPoint_GenTk",
    "GeneralProperties/TrackEtaErr_ImpactPoint_GenTk",
    "GeneralProperties/TrackPErrOverP_ImpactPoint_GenTk",
    "GeneralProperties/TrackPtErrOverPt_ImpactPoint_GenTk",
    "GeneralProperties/TrackPhiErr_ImpactPoint_GenTk",
    "GeneralProperties/TrackPzErrOverPz_ImpactPoint_GenTk",

]

#Track properties available/needed for "full" tracks only
fullTrackProperties = [
    "GeneralProperties/SIP2DToPV_GenTk",
    "GeneralProperties/SIP3DToPV_GenTk",
    "GeneralProperties/SIPDxyToBS_GenTk",
    "GeneralProperties/SIPDxyToPV_GenTk",
    "GeneralProperties/SIPDzToBS_GenTk",
    "GeneralProperties/SIPDzToPV_GenTk",
    "LUMIanalysis/NumberEventsVsLUMI",
    "PUmonitoring/NumberEventsVsGoodPVtx",
]