#Track properties available for both pixel tracks and "full" tracks
vertexProperties = [
    "Alignment/chi2ndf",
    "Alignment/chi2prob",
    "Alignment/dxyErrVsEta_pt1",
    "Alignment/dxyErrVsEta_pt10",
    "Alignment/dxyErrVsPhi_pt1",
    "Alignment/dxyErrVsPhi_pt10",
    "Alignment/dxyErr_pt1",
    "Alignment/dxyErr_pt10",
    "Alignment/dxyzoom",
    "Alignment/dzErrVsEta_pt1",
    "Alignment/dzErrVsEta_pt10",
    "Alignment/dzErrVsPhi_pt1",
    "Alignment/dzErrVsPhi_pt10",
    "Alignment/dzErr_pt1",
    "Alignment/dzErr_pt10",
    "Alignment/dzVsEta_pt1",
    "Alignment/dzVsEta_pt10",
    "Alignment/dzVsPhi_pt1",
    "Alignment/dzVsPhi_pt10",
    "Alignment/dz_pt1",
    "Alignment/dz_pt10",
    "Alignment/eta_pt1",
    "Alignment/eta_pt10",
    "Alignment/ntracks",
    "Alignment/phi_pt1",
    "Alignment/phi_pt10",
    "Alignment/sumpt",
    "Alignment/weight",

    "hltOnlineBeamSpot/bsBeamWidthX",
    "hltOnlineBeamSpot/bsBeamWidthY",
    "hltOnlineBeamSpot/bsDxdz",
    "hltOnlineBeamSpot/bsDydz",
    "hltOnlineBeamSpot/bsSigmaZ",
    "hltOnlineBeamSpot/bsX",
    "hltOnlineBeamSpot/bsY",
    "hltOnlineBeamSpot/bsZ",
]

hltPixelVertices = [
    "hltPixelVertices/goodvtxNbr",
    "hltPixelVertices/otherDiffX",
    "hltPixelVertices/otherDiffY",
    "hltPixelVertices/otherErrX",
    "hltPixelVertices/otherErrY",
    "hltPixelVertices/otherErrZ",
    "hltPixelVertices/otherPosX",
    "hltPixelVertices/otherPosY",
    "hltPixelVertices/otherPosZ",
    "hltPixelVertices/otherType",
    "hltPixelVertices/otherVtxChi2",
    "hltPixelVertices/otherVtxNans",
    "hltPixelVertices/otherVtxNdf",
    "hltPixelVertices/otherVtxProb",
    "hltPixelVertices/otherVtxScore",
    "hltPixelVertices/otherVtxTrksNbr",
    "hltPixelVertices/otherVtxTrksWeight",
    "hltPixelVertices/tagDiffX",
    "hltPixelVertices/tagDiffY",
    "hltPixelVertices/tagErrX",
    "hltPixelVertices/tagErrY",
    "hltPixelVertices/tagPosX",
    "hltPixelVertices/tagPosY",
    "hltPixelVertices/tagPosZ",
    "hltPixelVertices/tagType",
    "hltPixelVertices/tagVtxChi2",
    "hltPixelVertices/tagVtxNans",
    "hltPixelVertices/tagVtxNdf",
    "hltPixelVertices/tagVtxProb",
    "hltPixelVertices/tagVtxScore",
    "hltPixelVertices/tagVtxTrksNbr",
    "hltPixelVertices/tagVtxTrksWeight",
    "hltPixelVertices/vtxNbr",
]
hltVerticesPFFilter     = [p.replace('hltPixelVertices', 'hltVerticesPFFilter')     for p in hltPixelVertices]
hltTrimmedPixelVertices = [p.replace('hltPixelVertices', 'hltTrimmedPixelVertices') for p in hltPixelVertices]
